[build]
  command = "npm run build"
  publish = ".next"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
    from = "/_next/static/*"
    to = "/static/:splat"
    status = 301
    force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"